---
  - name: debug msg
    debug: msg=" {{ ansible_distribution }}  {{ ansible_distribution_major_version }} {{ nrpe.rpm }}"
  - name: Install epel
    yum: name={{ nrpe.rpm }} state=present
  - name: iptable install
    yum: name=iptables state=present
  - name: Install epel-release
    #yum: name={{ item }} enablerepo=extras update_cache=yes state=present
    yum: name={{ item }} update_cache=yes state=present
    with_items: "{{ nrpe.packages }}"
       #- epel-release
       #- nrpe
       #- nagios-plugins-all
#no need to open on openstack instance
  #- name: firewall setting
    #shell: "{{ nrpe.openPort }}"
# Make sure nrpe is running.
  - name: Ensure NRPE is running
    service: name={{ nrpe.service }} state=started enabled=yes
# Restart if config changes detected.
  - name: Update NPRE CONFIGS
    template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg
    notify:
    - restart nrpe
