
icinga2:
  url: http://packages.icinga.org/epel/ICINGA-release.repo
  key: http://packages.icinga.org/icinga.key
commands:
  - "icingacli setup token create"
  #- "icingacli setup config webserver apache --document-root /usr/share/icingaweb2/public > /etc/httpd/conf.d/icingaweb2.conf"
apache: httpd
