nrpe:
  rpm: http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  service: nrpe
  openPort: "iptables -A INPUT -p tcp --dport 5667 -j ACCEPT"
  packages:
  - epel-release
  - nrpe
  - nagios-plugins-all
  - nagios-plugins-nrpe
