---
  - name: add key
    shell: rpm --import {{ icinga2.centos6.repo_key }}
  - name: add repo
    shell: curl -o /etc/yum.repos.d/ICINGA-release.repo {{ icinga2.centos6.repo_url }}
  - name: makecache
    shell: yum makecache
  - name: Install ICINGA2
    yum: name=icinga2 state=present
  - name: Start icinga2
    service: name=icinga2 state=started enabled=yes 
