---

- include_vars: "variables.yml"
- include_vars: "ssl_keys.yml"
- include: icinga2.yml
  become: yes
  become_method: sudo
- include: icinga2web.yml
  become: yes
  become_method: sudo
- include: addUser.yml
  become: yes
  become_method: sudo
